apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: fetch-container
              image: curlimages/curl:latest  # Use a container with curl to make HTTP requests
              args:
                - /bin/sh
                - -c
                - "curl http://scrubber:80/fetch -s"
          restartPolicy: OnFailure
